author:
  name: "Tamas Kovacs"
  email: kovacstamasx@gmail.com
  avatar: "/assets/images/photo.jpg"
  bio: "Software engineer"
  location: "Erd, Hungary"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kovacstamasx"

title: Coding stuff explained
description: >- # this means to ignore newlines until "baseurl:"
  Software engineering practices, patterns explained.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://kovacstamasx.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username: kovacstamasx

# Build settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"
paginate: 5 # amount of posts to show
paginate_path: /page:num/
atom_feed:
  hide: true
include:
  - "_pages"

plugins:
  - jekyll-feed
  - jekyll-include-cache